CHANGELOG.md
lib/ethon/easy/informations.rb
spec/ethon/easy/informations_spec.rb
spec/ethon/easy/mirror_spec.rb

Added `redirect_time` value to available informations and `Easy::Mirror` so it can be used from `typhoeus` (upcoming PR). This will have to be published before the typhoeus PR.

Added redirect_time to available informations

---

lib/ethon/curls/classes.rb
lib/ethon/curls/constants.rb
lib/ethon/curls/functions.rb
lib/ethon/easy.rb
lib/ethon/easy/features.rb
lib/ethon/easy/informations.rb
spec/ethon/easy/features_spec.rb
spec/ethon/easy/informations_spec.rb
spec/ethon/easy/options_spec.rb

This is a first step to improve the timeout handling in typhoeus. It exposes curl_version_info and uses it to provide a supports_timeout_ms? helper. *This still needs verification* The benefit over just checking for c-ares in the version string (in addition to using the proper api to query it) is that it should also work for the threaded resolver and other (future) async resolvers.

[WIP] Exposing curl_version_info to ruby, supports_asynch_dns? helper

---

lib/ethon/easy/http/actionable.rb
lib/ethon/easy/http/postable.rb
lib/ethon/easy/http/putable.rb
lib/ethon/easy/queryable.rb
lib/ethon/version.rb
spec/ethon/easy/http/post_spec.rb
spec/ethon/easy/http/put_spec.rb
spec/ethon/easy/queryable_spec.rb

Rack applications expect
```ruby
foo: ['bar', 'baz']
```
to be encoded as:
```
foo[]=bar&foo[]=baz
```
whilst Ethon by default encodes it as:
```
foo[0]=bar&foo[1]=baz
```
This patch adds an `array_encoding` option to `Ethon::Easy`. If it set to `:rack`, then arrays are encoded the Rack way, both in `params: {}` and in `body: {}`. Any other value retains the current behaviour.
The option can be forwarded directly from `Typhoeus::Request.new`.
This implements typhoeus/typhoeus#424.

Add option to enable Rack-like encoding of array parameters

---

lib/ethon/curl.rb
lib/ethon/curls/functions.rb
lib/ethon/easy/operations.rb
spec/ethon/curl_spec.rb
spec/ethon/easy/operations_spec.rb

Due to some forking issues in Passenger it became necessary to clean up some things before Passenger spawned its worker processes.  This exposes the global clean up in libcurl and adds a method to Easy to allow for the immediate release of the ffi autopointer and run the easy cleanup.

Add global and easy clean up methods 

---

lib/ethon/multi/operations.rb

Attempt to resolve typhoeus/ethon issue #31.
Redo the select when it returns EINTR (errno==4), indicating that it has
been interrupted by the exection of a signal handler.  No attempt is
made to set a new timeout since that is non-portable (and straces
indicates some fractional second timeout values being passed). This is
intended to be, at worst, waiting up to twice as long as the timeout
given in the event of a signal, which is argubly better than fully
aborting on receiving a signal that has a signal handler installed.
It makes more sense to do this in ethon than in the calling code because
multiple libcurl interfaces are being used within the set_fds method:
both Curl.multi_fdset and Curl.select, and the reinvocation of select
should have the same fdsets, which wouldn't strictly be …

redo select on EINTR

---

lib/ethon/easy/queryable.rb

To support APIs that require arrays to be handled as multiple instances of the same parameter.
Example: a: [1, 2, 3] => "?a=1&a=2&a=3"

Added option for :multi array params

---

CHANGELOG.md
lib/ethon/easy.rb
lib/ethon/easy/http/actionable.rb
lib/ethon/easy/http/postable.rb
lib/ethon/easy/options.rb
spec/ethon/easy/http/get_spec.rb
spec/ethon/easy/http/post_spec.rb
spec/ethon/easy/options_spec.rb
spec/ethon/easy_spec.rb

Sometimes it's necessary to disable the built-in escaping of parameters, whether in URL queries or request bodies.
In my use-case, this is required in order to perform certain [security checks](https://github.com/Arachni/arachni/issues/626).
In addition, I've been able to reduce overhead by caching my own escaping operation as I'm performing thousands of requests with many similarities.
There probably are more use-cases where this can be useful.

Added support for optional escaping of params

---

lib/ethon.rb
spec/ethon/easy/queryable_spec.rb

This PR does two things in relation to issue https://github.com/typhoeus/ethon/issues/109. 
1) Fixes a false positive in the mime types spec (remove_const was in the wrong spec context, and wasn't reset between tests, so I instead use hide_const and put it in the correct spec context)
2) Allows ethon to use mime/types/columnar instead of the default to reduce memory usage. (see https://github.com/mime-types/ruby-mime-types/blob/b83af2c/README.rdoc#columnar-store). Although it was possible to trigger this behavior manually (https://twitter.com/schneems/status/603227060199272448), many people aren't aware of this, and I think it makes sense to default to the columnar store, similar to how the ruby mail gem does (https://github.com/mikel/mail/blob/dc0f89bb33722ec1e6fa404a34055fe6e0189651/lib/ …

Mime types columnar

---

.travis.yml
Gemfile
lib/ethon/curls/options.rb
lib/ethon/easy/operations.rb
lib/ethon/easy/options.rb
spec/ethon/easy/operations_spec.rb
spec/support/server.rb

Basically reducing of string allocations all over the place for the default/easy case.
[Speed is slightly increased](https://gist.github.com/ojab/8cc143e1be7dc8b0c005), memory usage is slightly reduced: simple testcase
```ruby
#!/usr/bin/env ruby
require 'ethon'
require 'memory_profiler'
URL = 'http://localhost:4567/none'.freeze
report = MemoryProfiler.report do
e_orig = Ethon::Easy.new(url: URL)
10_000.times do
e = e_orig.dup
e.perform
end
end
report.pretty_print
```
reports before:
```
Total allocated: 13629088 bytes (150094 objects)
Total retained:  1050264 bytes (12 objects)
allocated memory by gem
-----------------------------------
8308112  ethon/lib
4120080  ffi-1.9.10
1200352  other
544  ruby-2.3.0/lib
```
and after
```
Total allocated: 11787601 bytes (130058 objects)
Total …
```

Various cleanups

---

.travis.yml
Gemfile
lib/ethon/curls/functions.rb
lib/ethon/easy.rb
lib/ethon/easy/operations.rb
spec/ethon/easy_spec.rb
spec/support/server.rb

Handy if multiple similar requests should be done, i. e.:
```ruby
easy = Ethon::Easy.new(timeout: 5, …)
[url1, url2, url3].each do |url|
e = easy.dup
e.url = url
e.perform
end
```
saves a bunch of allocations/memory. This can be used even if block with e.perform is executed in multiple threads simultaneously (reusing of `easy` fails in this case).

Expose curl_easy_duphandle as Ethon::Easy.dup

---

CHANGELOG.md
lib/ethon/easy/mirror.rb
spec/ethon/easy/mirror_spec.rb

Methods that just create static objects cost us the object allocation + method call, better use constants instead.

Easy::Mirror: Reduced object allocations and method calls

---

lib/ethon/easy.rb
spec/ethon/easy_spec.rb

There is an error in my .dup implementation, now it's fixed.

We actually want to reset callbacks for duplicated handle, not original

---

Gemfile
spec/ethon/easy/informations_spec.rb
spec/ethon/easy/operations_spec.rb

1. Correct Rake dependency for older Rubies
2. RSpec upgraded to 3.4, deprecations resolved
Perhaps jruby-head tests should go to allowed failures.

Update Rake and RSpec

---

lib/ethon/curls/infos.rb

This is a fix for for issue #124 where in a JRuby multithreaded app the wrong values will get set because of using the same pointer

Use different pointers for every get_info_* method to avoid using the same pointer

---

lib/ethon/easy/operations.rb

It's the logger's responsibility whether or not to log an event based on the log level used.

Remove log level check

---

Gemfile

It seems as if json >= 2 requires ruby 2 or later. This adds the fix also found in the Typhoeus Gemfile.

Fix json gem related Travis failure

---

lib/ethon/curls/options.rb

This should provide access to curl's option [CURLOPT_UNIX_SOCKET_PATH](https://curl.haxx.se/libcurl/c/CURLOPT_UNIX_SOCKET_PATH.html)

Add unix socket path option.

---

lib/ethon/curls/options.rb

Discovered this while adding https://github.com/typhoeus/ethon/pull/120
The current functionality will just result in nil.to_i (0) being blindly passed through. If the change here isn't an appropriate solution, maybe an error should be raised instead?

allow passing int values to :enum or :bitmask opts

---

lib/ethon/easy/header.rb
spec/ethon/easy/header_spec.rb

Currently, there's not a super-easy way to pass a header with an empty value (e.g., `X-Foo: `) in Typhoeus or Ethon. If an empty string is passed in as the header value, then currently the header is omitted from the request altogether. This is due to how curl historically treated empty values (see [https://curl.haxx.se/mail/lib-2010-08/0174.html](https://curl.haxx.se/mail/lib-2010-08/0174.html)). Curl 7.23.0 (released November 2011) added a more standard way to pass empty values, but it requires special syntax of using a semicolon terminator.
This changes Ethon's behavior, so that when an empty string is passed as the value of a header, it gets sent by curl as an empty HTTP header, rather than omitting the header. A nil value will still omit the header. This seems like a more intuitive …

Add support for sending empty header values

---

lib/ethon/easy/form.rb
lib/ethon/easy/http/actionable.rb
lib/ethon/easy/options.rb
spec/ethon/easy/form_spec.rb
spec/ethon/easy/options_spec.rb

When using Typhoeus we noticed we weren't able to force multipart-form-data for form submission if no file is present (it automatically does it if files are present). However there are services out there (not just HTTP file uploads) that handle their forms in multipart-form-data format for variables even if a file isn't submitted, so forcing is sometimes necessary.
This simple PR allows us to submit forms to those services by forcing multipart-form-data generation even if no file is present. It's designed as an option you include in the Request.new() call in Typhoeus, but the work is done inside of Ethon because all the action happens there. Changes were kept to a minimum possible to achieve this feature. No changes were required in Typhoeus for this to function.
**An example request …

Changes for Ethon to allow multipart-form-data forcing 

---

lib/ethon/easy/queryable.rb
spec/ethon/easy/queryable_spec.rb

So my usecase is that a file is being uploaded to my rails server. Rails gives me a tempfile that I then want to upload to another service. I need to specify the filename and the content type of the file when I upload it to the other service using multi-part form data. By adding the `params_encoding` `:none` option it allows me to specify all of the parts of the form data manually without needing to worry about the encoding munging things. This is what you can do once this is merged:
```ruby
Typhoeus::Request.new(
url,
params: {
version: api_version
},
followlocation: true,
method: :post,
body: {
file: [
params[:file].original_filename,
params[:file].content_type,
params[:file].path
]
},
params_encoding: :none
)
```

Add params_encoding :none

---

lib/ethon/curls/options.rb
lib/ethon/multi/options.rb

A new bitset `CURLPIPE_MULTIPLEX` was added to [the `CURLMOPT_PIPELINING` option](https://curl.haxx.se/libcurl/c/CURLMOPT_PIPELINING.html) in version 7.43.0, but at the time of writing `Ethon` only allowed for setting `0` (`CURLPIPE_NOTHING`) or `1` (`CURLPIPE_HTTP1`) to `CURLMOPT_PIPELINING`. This made sence when it only had two bitsets, but now there are three, and it makes more sense to use `:int` rather than `:bool`.
I confirmed multiplexing works as expected by running the following code:
```ruby
require 'ethon'
url = "https://www.google.com/"
multi = Ethon::Multi.new
multi.pipelining = 2
multi.add Ethon::Easy.new(url: url, verbose: true, http_version: :httpv2_0, pipewait: true)
multi.add Ethon::Easy.new(url: url, verbose: true, http_version: :httpv2_0, pipewait: true)
multi.add …
```

Add support for CURLPIPE_MULTIPLEX

---

lib/ethon/curls/codes.rb
lib/ethon/easy.rb

Fixes https://github.com/typhoeus/ethon/issues/157
/cc @PericlesTheo

Remove ssl_cacert from return codes

---

lib/ethon/easy/operations.rb

This change fixes intermittent segfaults.
Unfortunately I don't have an easily reproducible test-case but this change seems to 
fix segfaults for a live system.

Easy::Operations#handle: Thread-safe cleanup

---

lib/ethon.rb
lib/ethon/curls/classes.rb
lib/ethon/libc.rb
spec/ethon/libc_spec.rb

As per the linux foundation deprecation note here:-
http://refspecs.linux-foundation.org/LSB_4.0.0/LSB-Core-generic/LSB-Core-generic/baselib-getdtablesize.html
This change keeps the gem up to date as this function is removed from
various platforms and allows it to run on aarch32/64.

Replace deprecated getdtablesize with sysconf

---

ethon.gemspec
lib/ethon/curls/functions.rb
lib/ethon/curls/infos.rb
lib/ethon/curls/options.rb

closes #180
As explained in #180, the definition of some libcurl functions in `lib/ethon/curls/functions.rb` was not in line with the definition in the libcurl C headers. This PR fixes this problem.
As I was told in https://github.com/typhoeus/ethon/issues/180#issuecomment-788652324 that supporting older versions of ffi was not needed, so I tried to go for what seemed to end with the cleanest code, requiring ffi 1.5.0.
In the [patch](https://gist.github.com/vincentisambart/c78e9df22d0d4851c1e1d150ac26e5d1) I initially wrote and linked in the issue, I went for the safest route, only modifying `lib/ethon/curls/functions.rb`, adding `easy_setopt_*` and `multi_setopt_*` functions with the old signatures that called the new varargs version. This PR modifies more code and so is probably more …

Use the proper varargs definition of libcurl functions

---

README.md

Hey 👋🏻 
Just a quick readme fix — noticed that status badge does not have a link and also there was an extra `[` before it.

chore: fix status badge

---

lib/ethon/curls/options.rb

Support for HTTPS proxies was added to libcurl in version 7.52.0. This
commit makes it usable through ethon and typhoeus.
https://curl.se/libcurl/c/CURLOPT_PROXYTYPE.html

Add support for HTTPS proxies

---

lib/ethon.rb
lib/ethon/curls/classes.rb
lib/ethon/libc.rb
spec/ethon/libc_spec.rb

Reverts typhoeus/ethon#166 - see #185 
Although I personally don't see this as an issue it's annoying for enough of people, so reverting.

Revert "Replace deprecated getdtablesize with sysconf"

---

lib/ethon/easy/operations.rb

This reverts commit b4899b952f85d089358f599c71b0cf7b03db6c39.
Fix #194

Revert "Easy::Operations#handle: Thread-safe cleanup (#136)"

---

lib/ethon/curls/constants.rb
lib/ethon/curls/functions.rb
lib/ethon/curls/options.rb
lib/ethon/curls/settings.rb
lib/ethon/multi.rb
lib/ethon/multi/operations.rb
spec/ethon/multi/options_spec.rb
spec/ethon/multi_spec.rb

This PR implements bindings for `curl_multi_socket_action` on the `Ethon::Multi` object, allowing simple integration between Ethon and an external IO loop.
This primarily introduces a new `execution_mode` option which, when provided, changes the `Multi` object from having a complete internal `perform` implementation with `curl_multi_perform`, to an externally driven one using `curl_multi_socket_action` by calling `socket_action` any time a socket is ready, or when it times out. The ability to choose between the `perform` and `socket_action` aligns with the way underlying Curl multi objects work, and the calling pattern for `Multi#socket_action` aligns with the [typical usage documented in curl](https://curl.se/libcurl/c/curl_multi_socket_action.html).
As part of this change, this PR also …

Add optional socket_action mode to Ethon::Multi

---

lib/ethon/curls/options.rb

Add support for own SSL/TLS settings for HTTPS proxy, which might be separate from general SSL/TLS settings. 
Supported since libcurl 7.52.0.
Original commit link: https://github.com/curl/curl/commit/cb4e2be7c6d42ca0780f8e0a747cecf9ba45f151

HTTPS proxies - support for own SSL/TLS session

---

lib/ethon/curls/classes.rb

FD Size: Add default cap of 65536 and ETHON_FD_SIZE to override it

---

lib/ethon/curls/options.rb

Support for TCP Fast Open (TFO) was added to libcurl in version 7.49.0[1] through CURLOPT_TCP_FASTOPTION[2].
[1]: https://github.com/curl/curl/blob/curl-7_49_0/docs/libcurl/symbols-in-versions#L541
[2]: https://curl.se/libcurl/c/CURLOPT_TCP_FASTOPEN.html
Rebased version of #203 to re-trigger the test-suite.

Add :tcp_fastopen option

---

README.md

Resolves https://github.com/typhoeus/ethon/issues/224
Thanks to https://github.com/codealchemy for pointing out what was causing the example not to work.

Fix missing parenthesis in example

---

ethon.gemspec

There are several files in the gem package that aren't useful for downstream projects. Removing these files reduces the gem package size from **59K** to **39K**!
<details><summary>gem contents diff</summary>
```diff
< .github/workflows/ruby.yml
< .gitignore
< .rspec
CHANGELOG.md
< Gemfile
< Guardfile
LICENSE
README.md
< Rakefile
ethon.gemspec
lib/ethon.rb
lib/ethon/curl.rb
lib/ethon/curls/classes.rb
lib/ethon/curls/codes.rb
lib/ethon/curls/constants.rb
lib/ethon/curls/form_options.rb
lib/ethon/curls/functions.rb
lib/ethon/curls/infos.rb
lib/ethon/curls/messages.rb
lib/ethon/curls/options.rb
lib/ethon/curls/settings.rb
lib/ethon/easy.rb
lib/ethon/easy/callbacks.rb
lib/ethon/easy/debug_info.rb
lib/ethon/easy/features.rb
lib/ethon/easy/form.rb
lib/ethon/easy/header.rb
lib/ethon/easy/http.rb …
```

Remove development and test files from the gem package

---

.github/workflows/ruby.yml

Ruby 3.2 has [been released](https://www.ruby-lang.org/en/news/2022/12/25/ruby-3-2-0-released/)! Let's add it and Ruby 3.1 to the build matrix for confidence in compatibility.

CI: add Ruby 3.1 and 3.2 to the test matrix

---

Gemfile
spec/support/localhost_server.rb
spec/support/server.rb

`Rack::Handler::WEBrick` was extracted from Rack to Rackup. Use this as an opportunity to move from WEBrick specific handler to generic `Rackup::Handler`. This eventually allows to specify server by `RACKUP_HANDLER` environment variable. ATM, Gemfile still specifies WEBrick.
This is related to #243 and allows to used e.g. Puma for experimenting

Use `Rackup::Handler.default` for Rack 3 compatibility

---

spec/ethon/easy/informations_spec.rb

This pr modifies the request_size test so that we skip it on versions of libcurl affected by a bug in CURLINFO_REQUEST_SIZE (https://github.com/curl/curl/issues/13269). The bug was fixed in 8.8.0 (https://curl.se/ch/8.8.0.html).
Unfortunately, the macos runner for our gh actions uses ones of the affected versions. Since this is an issue with libcurl itself, I think its fine to skip the test on the affected versions. I've also ran our tests against the surrounding versions to ensure this was the issue:
> Test run summary by libcurl version
>   • 8.5.0: 578 examples, 0 failures, 2 pending
>   • 8.6.0: 578 examples, 0 failures, 2 pending
>   • 8.7.0: 578 examples, 1 failure, 2 pending (request_size returned 0)
>   • 8.7.1: 578 examples, 1 failure, 2 pending (request_size returned 0)
>   • …

Skip a test due to libcurl 8.7.x bug in CURLINFO_REQUEST_SIZE

---

ethon.gemspec
lib/ethon/loggable.rb
profile/benchmarks.rb
spec/ethon/easy/queryable_spec.rb
spec/spec_helper.rb

This magic comment is not needed anymore because the default encoding of source code files assumed by Ruby 2 is utf-8, and the minimum required Ruby version is 2.6
Auto-fixed via:
```
rubocop -a --only Style/Encoding
```
---
`require_relative` has been introduced in Ruby 1.9.2 and is available in all supported Ruby versions

Remove redundant encoding and require_relative check

---

ethon.gemspec

As a popular gem (over 180 million total downloads), `ethon` implicitly requires that all privileged operations by any of the owners require OTP.
By explicitly setting `rubygems_mfa_required` metadata, the gem will show "NEW VERSIONS REQUIRE MFA" and "VERSION PUBLISHED WITH MFA" in the sidebar at https://rubygems.org/gems/ethon
This commit also introduces additional metadata
Ref:
- https://blog.rubygems.org/2022/08/15/requiring-mfa-on-popular-gems.html
- https://guides.rubygems.org/mfa-requirement-opt-in/
---
metadata verified via
```
$ gem build
$ gem spec -l ethon-0.17.0.gem 
metadata:
bug_tracker_uri: https://github.com/typhoeus/ethon/issues
changelog_uri: https://github.com/typhoeus/ethon/blob/v0.17.0/CHANGELOG.md
documentation_uri: https://www.rubydoc.info/gems/ethon/0.17.0 …
```

Opt-in for MFA requirement explicitly

---

spec/support/localhost_server.rb

Ensure the spec helper's WEBrick server starts and is detected reliably on recent macOS:
- Bind WEBrick explicitly to `localhost` and probe readiness via `127.0.0.1` to avoid IPv6/IPv4 `localhost` resolution mismatches that triggered Net::OpenTimeout during boot. (Copilot)
- Use a single Rackup/Rack WEBrick handler constant consistently
- Keep WEBrick for tests since it supports custom methods (e.g. `PURGE`) that stricter servers reject.
- Trap INT and call handler.shutdown via the shared constant to cleanly stop the server process, helping prevent orphaned servers and file descriptor leaks (seen as `Errno::EMFILE` after reruns).
- Replace deprecated top-level `TimeoutError` with `Timeout::Error` and require `timeout`
With these changes, the test server comes up promptly and the suite no …

Stabilize test server boot on macOS

---

lib/ethon/easy/callbacks.rb
spec/ethon/easy/callbacks_spec.rb
spec/ethon/easy/http_spec.rb

PR #221 introduced the ability to abort a request from  the `on_headers` user defined callbacks.
Before this PR , `on_headers` callbacks were called exactly one time and only once all headers are in, including from multiple redirects. This is the expected value for `response_headers` inside a `on_headers` callback for a request that followed a redirect:
```
HTTP/1.1 302 Found
Location: http://localhost:3001/
Content-Type: text/html;charset=utf-8
Content-Length: 0
X-Xss-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
Server: WEBrick/1.9.1 (Ruby/3.4.5/2025-07-16)
Date: Wed, 27 Aug 2025 13:31:38 GMT
Connection: Keep-Alive
HTTP/1.1 200 OK
Content-Type: text/html;charset=utf-8
Content-Length: 653
X-Xss-Protection: 1; mode=block
X-Content-Type-Options: …
```

Fix `on_headers` callbacks being called early

---

lib/ethon/easy/callbacks.rb

Replace broken ssl data with summary
